<?php
/**
 * Created by Cessel's WEBGate Studio.
 * User: Cessel
 * Date: 06.07.2021
 * Time: 7:54
 */

global $blog_id;
if( function_exists('acf_add_local_field_group') && $blog_id !== 1 ):

	acf_add_local_field_group(array(
		'key' => 'group_59eafa45efe9c',
		'title' => 'Баннеры на главной',
		'fields' => array(
			array(
				'key' => 'field_59eafa5252626',
				'label' => 'Баннеры',
				'name' => 'баннеры',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Добавить',
				'sub_fields' => array(
					array(
						'key' => 'field_59eafa6752627',
						'label' => 'Картинка для баннера',
						'name' => 'img',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5a009d5039cf4',
						'label' => 'тип курса',
						'name' => 'тип_курса',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_59eafa7a52628',
						'label' => 'Слоган на баннере',
						'name' => 'слоган_на_баннере',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_59eafaa75262b',
						'label' => 'Подзаголовок на баннере',
						'name' => 'подзаголовок_на_баннере',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_59eafa925262a',
						'label' => 'ссылка с кнопки',
						'name' => 'ссылка_с_кнопки',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'new_front-page.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5c80006cd978e',
		'title' => 'Другие настройки главной страницы',
		'fields' => array(
			array(
				'key' => 'field_5c80007734d09',
				'label' => 'Блок видео',
				'name' => 'блок_видео',
				'type' => 'text',
				'instructions' => 'Вставить ссылку на видео с ютуба',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'new_front-page.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5d5165ae03373',
		'title' => 'Настройки для контактов',
		'fields' => array(
			array(
				'key' => 'field_5d5168012c13d',
				'label' => 'Заголовок как пройти до школы',
				'name' => 'заголовок_как_пройти_до_школы',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d5165b7e87cd',
				'label' => 'Фотографии как пройти до школы',
				'name' => 'фотографии_как_пройти_до_школы',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Добавить',
				'sub_fields' => array(
					array(
						'key' => 'field_5d5165f2e87ce',
						'label' => 'Фото',
						'name' => 'фото',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5d5165fde87cf',
						'label' => 'Подпись к фото',
						'name' => 'подпись_к_фото',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5fa7ca5d1f066',
				'label' => 'Адреса',
				'name' => 'addresses',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa7ca6c1f067',
						'label' => 'Наименование',
						'name' => 'label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa7ca741f068',
						'label' => 'Адрес - показываемый пользователю',
						'name' => 'address_shown',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa7cabb1f06b',
						'label' => 'Адрес для карты',
						'name' => 'address_map',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa7ca951f069',
						'label' => 'Широта',
						'name' => 'latitude',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa7caa01f06a',
						'label' => 'Долгота',
						'name' => 'longitude',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa7d20a5c167',
						'label' => 'Ссылка "Посмотреть на карте"',
						'name' => 'map_link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa7cf9f03683',
						'label' => 'Ссылка "Как проехать"',
						'name' => 'path_link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5fa802b860bfe',
				'label' => 'Контакты',
				'name' => 'contacts',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa802cc60bff',
						'label' => 'Наименование контакта',
						'name' => 'label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa802dd60c00',
						'label' => 'Значение контакта',
						'name' => 'value',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa802f260c01',
						'label' => 'Описание контакта',
						'name' => 'desc',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5fa80bccad232',
						'label' => 'Тип контакта',
						'name' => 'contact_type',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'tel' => 'Телефон',
							'messenger' => 'Мессенджер',
							'email' => 'Электронная почта',
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'contacts.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5e29a37d5e7f5',
		'title' => 'Настройки для пользователей',
		'fields' => array(
			array(
				'key' => 'field_5e29a3c6d7413',
				'label' => 'Ваше фото',
				'name' => 'comment_user_photo',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'comment',
					'operator' => '==',
					'value' => 'all',
				),
			),
			array(
				array(
					'param' => 'user_form',
					'operator' => '==',
					'value' => 'all',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));


	acf_add_local_field_group(array(
		'key' => 'group_5da9a126a1acd',
		'title' => 'Настройки сайта v.2',
		'fields' => array(
			array(
				'key' => 'field_5da9a98ebc9c9',
				'label' => 'JSON запрос с параметрами группы VK',
				'name' => 'vk_group_params',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5da9a138e28ca',
				'label' => 'JSON запрос с данными о группе VK',
				'name' => 'vk_group_json',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_59e237cc95f78',
		'title' => 'Наши преимущества на главной',
		'fields' => array(
			array(
				'key' => 'field_59eafb254d9a8',
				'label' => 'Преимущества',
				'name' => 'преимущества',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Добавить',
				'sub_fields' => array(
					array(
						'key' => 'field_59e22ae1e690b',
						'label' => 'Изображение преимущества',
						'name' => 'img',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'return_format' => 'url',
						'min_width' => 0,
						'min_height' => 0,
						'min_size' => 0,
						'max_width' => 0,
						'max_height' => 0,
						'max_size' => 0,
						'mime_types' => '',
					),
					array(
						'key' => 'field_59e22b2be690c',
						'label' => 'Заголовок преимущества',
						'name' => 'заголовок_преимущества',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_59e22b4be690d',
						'label' => 'Описание преимущества',
						'name' => 'описание_преимущества',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => 'br',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page',
					'operator' => '==',
					'value' => '6',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'new_front-page.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_59e2386c65995',
		'title' => 'Работы преподавателей',
		'fields' => array(
			array(
				'key' => 'field_59e2388a29fae',
				'label' => 'Работы преподавателя',
				'name' => 'работы_преподавателя',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Добавить',
				'sub_fields' => array(
					array(
						'key' => 'field_59e2389829faf',
						'label' => 'Изображение',
						'name' => 'изображение',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'team',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_59eb1f92de143',
		'title' => 'Услуги',
		'fields' => array(
			array(
				'key' => 'field_59eb1fb162627',
				'label' => 'Услуги',
				'name' => 'услуги',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Добавить',
				'sub_fields' => array(
					array(
						'key' => 'field_59eb1fba62628',
						'label' => 'Изображение услуги',
						'name' => 'img',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_59eb1fd262629',
						'label' => 'Название услуги',
						'name' => 'название_услуги',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_59eb268e06235',
						'label' => 'Ссылка',
						'name' => 'ссылка',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'new_front-page.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_60ec0ee941188',
		'title' => 'Настройки для филиалов',
		'fields' => array(
			array(
				'key' => 'field_60ec0f02ac445',
				'label' => 'Настройки филиала',
				'name' => 'filial_defaults',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60ec0f28ac446',
						'label' => 'Контакты',
						'name' => 'contacts',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_60ec0f4cac447',
								'label' => 'Короткое имя контакта',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_60ec100bac448',
								'label' => 'Тип контакта',
								'name' => 'type',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'address' => 'Адрес',
									'phone' => 'Телефон',
									'email' => 'Email',
									'social' => 'Соц. сети',
								),
								'default_value' => array(
								),
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_60ec106cac449',
								'label' => 'Значение контакта',
								'name' => 'value',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_611008d1ed02e',
								'label' => 'Отображаемый адрес',
								'name' => 'address_shown',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_60ec100bac448',
											'operator' => '==',
											'value' => 'address',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_60ec1079ac44a',
								'label' => 'Иконка контакта',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'id',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_60ec10a1ac44c',
								'label' => 'Расположение',
								'name' => 'place',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'header' => 'В шапке',
									'footer' => 'В подвале',
									'contacts' => 'На странице контактов',
									'other' => 'Не указано',
								),
								'default_value' => array(
								),
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
						),
					),
					array(
						'key' => 'field_60ec129c72409',
						'label' => 'Часы работы',
						'name' => 'workhours',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_60ec12b87240b',
								'label' => 'Дни',
								'name' => 'days',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_60ec12cc7240c',
								'label' => 'Часы',
								'name' => 'hours',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_60ec12f9e2c12',
						'label' => 'Логотип в шапке',
						'name' => 'header_logo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_6110af2174314',
		'title' => 'Настройки для преподавателей',
		'fields' => array(
			array(
				'key' => 'field_6110af3294923',
				'label' => 'Имя сотрудника',
				'name' => 'team-name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6110af7594924',
				'label' => 'Должность сотрудника',
				'name' => 'team-role',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6110af7c94925',
				'label' => 'Краткая биография',
				'name' => 'team-bio',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_6110af9994926',
				'label' => 'Фото сотрудника',
				'name' => 'team-foto',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'team',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5dc3243923118',
		'title' => 'Настройки для расписания',
		'fields' => array(
			array(
				'key' => 'field_5dc32446c3cc9',
				'label' => 'Группа классов',
				'name' => 'class_group',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'group-add',
					'id' => '',
				),
				'collapsed' => 'field_5dc325c3c3cd2',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Добавить группу классов',
				'sub_fields' => array(
					array(
						'key' => 'field_5dc325c3c3cd2',
						'label' => 'Наименование группы',
						'name' => 'class_group_name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dc3245bc3cca',
						'label' => 'Класс',
						'name' => 'class',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'class-add',
							'id' => '',
						),
						'collapsed' => 'field_5dc325e2c3cd3',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => 'Добавить класс',
						'sub_fields' => array(
							array(
								'key' => 'field_5dc325e2c3cd3',
								'label' => 'Наименование класса',
								'name' => 'class_name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5dc32963edd36',
								'label' => 'День недели',
								'name' => 'week_day',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'weekday-add',
									'id' => '',
								),
								'collapsed' => 'field_5dc32983edd37',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Добавить день недели',
								'sub_fields' => array(
									array(
										'key' => 'field_5dc32983edd37',
										'label' => 'Наименование дня недели',
										'name' => 'day_name',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Понедельник' => 'Понедельник',
											'Вторник' => 'Вторник',
											'Среда' => 'Среда',
											'Четверг' => 'Четверг',
											'Пятница' => 'Пятница',
											'Суббота' => 'Суббота',
											'Воскресенье' => 'Воскресенье',
										),
										'default_value' => array(
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'return_format' => 'value',
										'ajax' => 0,
										'placeholder' => '',
									),
									array(
										'key' => 'field_5dc329a0edd38',
										'label' => 'Уроки',
										'name' => 'lessons',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => 'lesson-add',
											'id' => '',
										),
										'collapsed' => 'field_5dc3267c2f988',
										'min' => 0,
										'max' => 0,
										'layout' => 'table',
										'button_label' => 'Добавить урок',
										'sub_fields' => array(
											array(
												'key' => 'field_5dc3267c2f988',
												'label' => 'Название урока',
												'name' => 'lesson_name',
												'type' => 'radio',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array(
													'Живопись' => 'Живопись',
													'Рисунок' => 'Рисунок',
													'Композиция' => 'Композиция',
													'Занятие' => 'Занятие',
													'ИЗО' => 'ИЗО',
												),
												'allow_null' => 1,
												'other_choice' => 1,
												'save_other_choice' => 0,
												'default_value' => '',
												'layout' => 'vertical',
												'return_format' => 'value',
											),
											array(
												'key' => 'field_5dc3268a2f989',
												'label' => 'Начало и окончание урока',
												'name' => 'lesson_start',
												'type' => 'radio',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array(
													'10:10 – 10:50' => '10:10 – 10:50',
													'10:50 – 11:00' => '10:50 – 11:00',
													'11:00 – 11:40' => '11:00 – 11:40',
													'11:40 – 11:50' => '11:40 – 11:50',
													'11:50 – 12:30' => '11:50 – 12:30',
													'12:30 – 12:40' => '12:30 – 12:40',
													'12:40 – 13:20' => '12:40 – 13:20',
													'13:20 – 13:50' => '13:20 – 13:50',
													'13:50 – 14:30' => '13:50 – 14:30',
													'14:30 – 14:40' => '14:30 – 14:40',
													'14:40 – 15:20' => '14:40 – 15:20',
													'15:20 – 15:30' => '15:20 – 15:30',
													'15:30 – 16:10' => '15:30 – 16:10',
													'16:10 – 16:20' => '16:10 – 16:20',
													'16:20 – 17:00' => '16:20 – 17:00',
													'17:00 – 17:40' => '17:00 – 17:40',
													'17:40 – 17:50' => '17:40 – 17:50',
													'17:50 – 18:30' => '17:50 – 18:30',
													'18:30 – 18:40' => '18:30 – 18:40',
													'18:40 – 19:20' => '18:40 – 19:20',
													'19:20 – 19:30' => '19:20 – 19:30',
													'19:30 – 20:10' => '19:30 – 20:10',
													'20:10 – 20:20' => '20:10 – 20:20',
													'20:20 – 21:00' => '20:20 – 21:00',
												),
												'allow_null' => 0,
												'other_choice' => 1,
												'save_other_choice' => 1,
												'default_value' => '',
												'layout' => 'vertical',
												'return_format' => 'value',
											),
											array(
												'key' => 'field_5dc32a88108fc',
												'label' => 'Имя преподавателя',
												'name' => 'lesson_delay',
												'type' => 'select',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array(
													'Анохин Андрей Павлович' => 'Анохин Андрей Павлович',
													'Артемьева Евгения Александровна' => 'Артемьева Евгения Александровна',
													'Бергетова Надежда Вячеславовна' => 'Бергетова Надежда Вячеславовна',
													'Ильчук Лидия Андреевна' => 'Ильчук Лидия Андреевна',
													'Лычагин Сергей Адольфович' => 'Лычагин Сергей Адольфович',
													'Марковникова Виктория Александровна' => 'Марковникова Виктория Александровна',
													'Пуховский Виктор Николаевич' => 'Пуховский Виктор Николаевич',
													'Родин Андрей Юрьевич' => 'Родин Андрей Юрьевич',
													'Ростова Инга Борисовна' => 'Ростова Инга Борисовна',
													'Цой Ксения Владиславовна' => 'Цой Ксения Владиславовна',
													'Шевела Екатерина Александровна' => 'Шевела Екатерина Александровна',
													'Шуклина Виктория Ильинична' => 'Шуклина Виктория Ильинична',
												),
												'default_value' => array(
												),
												'allow_null' => 1,
												'multiple' => 0,
												'ui' => 1,
												'ajax' => 1,
												'return_format' => 'value',
												'placeholder' => '',
											),
										),
									),
								),
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-schedule.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;